2022-03-09 22:06:50,953 INFO    MainThread:5952 [wandb_setup.py:_flush():75] Loading settings from /home/rgundaka/.config/wandb/settings
2022-03-09 22:06:50,953 INFO    MainThread:5952 [wandb_setup.py:_flush():75] Loading settings from /central/groups/tensorlab/rgundaka/code/PINO/scripts/wandb/settings
2022-03-09 22:06:50,953 INFO    MainThread:5952 [wandb_setup.py:_flush():75] Loading settings from environment variables: {}
2022-03-09 22:06:50,953 WARNING MainThread:5952 [wandb_setup.py:_flush():75] Could not save program above cwd: /groups/tensorlab/rgundaka/code/PINO/run_pino2d_sa.py
2022-03-09 22:06:50,953 INFO    MainThread:5952 [wandb_setup.py:_flush():75] Inferring run settings from compute environment: {'program_relpath': None, 'program': '/groups/tensorlab/rgundaka/code/PINO/run_pino2d_sa.py'}
2022-03-09 22:06:50,953 INFO    MainThread:5952 [wandb_setup.py:_flush():75] Applying settings from <Settings {'_args': None, '_cli_only_mode': None, '_config_dict': None, '_cuda': None, '_debug_log': None, '_disable_meta': None, '_disable_stats': None, '_disable_viewer': None, '_except_exit': None, '_executable': None, '_internal_check_process': 8, '_internal_queue_timeout': 2, '_jupyter_name': None, '_jupyter_path': None, '_jupyter_root': None, '_os': None, '_python': None, '_require_service': None, '_runqueue_item_id': None, '_save_requirements': True, '_service_transport': None, '_start_datetime': None, '_start_time': None, '_tmp_code_dir': '/central/groups/tensorlab/rgundaka/code/PINO/scripts/wandb/run-None-None/tmp/code', '_unsaved_keys': None, 'allow_val_change': None, 'anonymous': None, 'api_key': '***REDACTED***', 'base_url': 'https://api.wandb.ai', 'code_dir': None, 'config_paths': None, 'console': 'auto', 'disable_code': None, 'disable_git': None, 'disabled': False, 'docker': None, 'email': None, 'entity': None, 'files_dir': '/central/groups/tensorlab/rgundaka/code/PINO/scripts/wandb/run-None-None/files', 'force': None, 'git_remote': 'origin', 'heartbeat_seconds': 30, 'host': None, 'ignore_globs': (), 'label_disable': None, 'launch': None, 'launch_config_path': None, 'log_dir': '/central/groups/tensorlab/rgundaka/code/PINO/scripts/wandb/run-None-None/logs', 'log_internal': '/central/groups/tensorlab/rgundaka/code/PINO/scripts/wandb/run-None-None/logs/debug-internal.log', 'log_symlink_internal': '/central/groups/tensorlab/rgundaka/code/PINO/scripts/wandb/debug-internal.log', 'log_symlink_user': '/central/groups/tensorlab/rgundaka/code/PINO/scripts/wandb/debug.log', 'log_user': '/central/groups/tensorlab/rgundaka/code/PINO/scripts/wandb/run-None-None/logs/debug.log', 'login_timeout': None, 'magic': None, 'mode': 'online', 'notebook_name': None, 'problem': 'fatal', 'program': None, 'program_relpath': None, 'project': None, 'quiet': None, 'reinit': None, 'relogin': None, 'resume': None, 'resume_fname': '/central/groups/tensorlab/rgundaka/code/PINO/scripts/wandb/wandb-resume.json', 'root_dir': '/central/groups/tensorlab/rgundaka/code/PINO/scripts', 'run_group': None, 'run_id': None, 'run_job_type': None, 'run_name': None, 'run_notes': None, 'run_tags': None, 'sagemaker_disable': None, 'save_code': None, 'settings_system': '/home/rgundaka/.config/wandb/settings', 'settings_workspace': '/central/groups/tensorlab/rgundaka/code/PINO/scripts/wandb/settings', 'show_colors': None, 'show_emoji': None, 'show_errors': True, 'show_info': True, 'show_warnings': True, 'silent': False, 'start_method': 'fork', 'strict': None, 'summary_errors': None, 'summary_warnings': 5, 'sweep_id': None, 'sweep_param_path': None, 'symlink': None, 'sync_dir': '/central/groups/tensorlab/rgundaka/code/PINO/scripts/wandb/run-None-None', 'sync_file': '/central/groups/tensorlab/rgundaka/code/PINO/scripts/wandb/run-None-None/run-None.wandb', 'sync_symlink_latest': '/central/groups/tensorlab/rgundaka/code/PINO/scripts/wandb/latest-run', 'system_sample': 15, 'system_sample_seconds': 2, 'tmp_dir': '/central/groups/tensorlab/rgundaka/code/PINO/scripts/wandb/run-None-None/tmp', 'username': None, '_console': <SettingsConsole.REDIRECT: 2>, '_jupyter': False, '_kaggle': False, '_noop': False, '_offline': False, '_quiet': None, '_show_info': True, '_show_warnings': True, '_show_errors': True, '_silent': False, '_strict': None, '_windows': False, 'is_local': False, 'run_mode': 'run', 'timespec': None, 'wandb_dir': '/central/groups/tensorlab/rgundaka/code/PINO/scripts/wandb/'}>
2022-03-09 22:06:50,955 INFO    MainThread:5952 [wandb_init.py:_log_setup():386] Logging user logs to /central/groups/tensorlab/rgundaka/code/PINO/scripts/wandb/run-20220309_220650-hfjob5zo/logs/debug.log
2022-03-09 22:06:50,955 INFO    MainThread:5952 [wandb_init.py:_log_setup():387] Logging internal logs to /central/groups/tensorlab/rgundaka/code/PINO/scripts/wandb/run-20220309_220650-hfjob5zo/logs/debug-internal.log
2022-03-09 22:06:50,956 INFO    MainThread:5952 [wandb_init.py:init():420] calling init triggers
2022-03-09 22:06:50,956 INFO    MainThread:5952 [wandb_init.py:init():427] wandb.init called with sweep_config: {}
config: {'data': {'datapath': '/groups/tensorlab/rgundaka/code/data/piececonst_r421_N1024_smooth2.mat', 'n_sample': 1, 'name': 'Darcy', 'nx': 421, 'offset': 1, 'sub': 7, 'total_num': 1024}, 'model': {'activation': 'gelu', 'fc_dim': 128, 'layers': [64, 64, 64, 64, 64], 'modes1': [20, 20, 20, 20], 'modes2': [20, 20, 20, 20], 'self_adaptive': True}, 'others': {'entity': 'rishigundakaram', 'group': 'darcy-finetune', 'project': 'sa-pino'}, 'sa_lr': 1, 'self_adaptive': False, 'train': {'base_lr': 0.0025, 'batchsize': 1, 'ckpt': '/groups/tensorlab/rgundaka/scripts/checkpoints/darcy-FDM/darcy-pino-nd.pt', 'epochs': 500, 'f_loss': 1.0, 'milestones': [100, 200, 300, 400], 'sa_lr': 0.01, 'save_dir': 'darcy-FDM-finetune', 'save_name': 'darcy-finetune-pino.pt', 'scheduler_gamma': 0.5, 'xy_loss': 0.0}}
2022-03-09 22:06:50,956 INFO    MainThread:5952 [wandb_init.py:init():471] starting backend
2022-03-09 22:06:50,956 INFO    MainThread:5952 [backend.py:_multiprocessing_setup():101] multiprocessing start_methods=fork,spawn,forkserver, using: spawn
2022-03-09 22:06:50,958 INFO    MainThread:5952 [backend.py:ensure_launched():219] starting backend process...
2022-03-09 22:06:51,001 INFO    MainThread:5952 [backend.py:ensure_launched():225] started backend process with pid: 6271
2022-03-09 22:06:51,018 INFO    MainThread:5952 [wandb_init.py:init():480] backend started and connected
2022-03-09 22:06:51,024 INFO    MainThread:5952 [wandb_init.py:init():550] updated telemetry
2022-03-09 22:06:51,156 INFO    MainThread:5952 [wandb_init.py:init():581] communicating current version
2022-03-09 22:06:51,964 WARNING MainThread:5952 [wandb_init.py:init():972] interrupted
Traceback (most recent call last):
  File "/home/rgundaka/miniconda3/envs/rishig/lib/python3.6/site-packages/wandb/sdk/wandb_init.py", line 951, in init
    run = wi.init()
  File "/home/rgundaka/miniconda3/envs/rishig/lib/python3.6/site-packages/wandb/sdk/wandb_init.py", line 583, in init
    current_version=wandb.__version__
  File "/home/rgundaka/miniconda3/envs/rishig/lib/python3.6/site-packages/wandb/sdk/interface/interface.py", line 92, in communicate_check_version
    ret = self._communicate_check_version(check_version)
  File "/home/rgundaka/miniconda3/envs/rishig/lib/python3.6/site-packages/wandb/sdk/interface/interface_shared.py", line 413, in _communicate_check_version
    result = self._communicate(rec)
  File "/home/rgundaka/miniconda3/envs/rishig/lib/python3.6/site-packages/wandb/sdk/interface/interface_shared.py", line 213, in _communicate
    return self._communicate_async(rec, local=local).get(timeout=timeout)
  File "/home/rgundaka/miniconda3/envs/rishig/lib/python3.6/site-packages/wandb/sdk/interface/router.py", line 37, in get
    is_set = self._object_ready.wait(timeout)
  File "/home/rgundaka/miniconda3/envs/rishig/lib/python3.6/threading.py", line 551, in wait
    signaled = self._cond.wait(timeout)
  File "/home/rgundaka/miniconda3/envs/rishig/lib/python3.6/threading.py", line 299, in wait
    gotit = waiter.acquire(True, timeout)
KeyboardInterrupt
